"""
=============================================================
Script 3 — Database Loader
=============================================================
Connects to PostgreSQL (marketplace_db) and bulk-loads the
cleaned CSV files into their corresponding tables.

Pre-requisites:
  • PostgreSQL running on localhost:5432
  • Database 'marketplace_db' created
  • Schema applied via sql/schema.sql
  • Cleaned CSVs generated by 2_etl_pipeline.py
=============================================================
"""

import os
import sys
from dotenv import load_dotenv

load_dotenv()

import pandas as pd
import psycopg2
from psycopg2 import sql as psql
from psycopg2.extras import execute_values

# --------------- PostgreSQL connection config ---------------
DB_CONFIG = {
    "host":     "localhost",
    "port":     5432,
    "database": "marketplace_db",
    "user":     "postgres",
    "password": os.environ.get("DB_PASSWORD"),
}

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "data")


def get_connection():
    """Create and return a psycopg2 connection."""
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        conn.autocommit = False
        print("✅  Connected to PostgreSQL")
        return conn
    except psycopg2.Error as e:
        print(f"❌  Database connection failed: {e}")
        sys.exit(1)


def load_table(conn, table_name: str, csv_file: str, columns: list):
    """
    Read a CSV and insert rows into *table_name* using batch insert.
    Columns list should match the CSV header order (excluding auto-PK
    if you want the DB to generate IDs — here we supply IDs from CSV).
    """
    filepath = os.path.join(DATA_DIR, csv_file)
    if not os.path.exists(filepath):
        print(f"⚠️   {csv_file} not found — skipping {table_name}")
        return

    df = pd.read_csv(filepath)
    df = df[columns]  # keep only the columns we need

    # Replace NaN with None for proper SQL NULL handling
    df = df.where(pd.notnull(df), None)

    cur = conn.cursor()

    # Build INSERT statement
    cols_str = ", ".join(columns)
    placeholders = ", ".join(["%s"] * len(columns))
    insert_sql = f"""
        INSERT INTO {table_name} ({cols_str})
        VALUES ({placeholders})
        ON CONFLICT DO NOTHING
    """

    try:
        rows = [tuple(row) for row in df.itertuples(index=False, name=None)]
        cur.executemany(insert_sql, rows)
        conn.commit()
        print(f"✅  {table_name:<20} ← {len(rows):>6,} rows loaded from {csv_file}")
    except psycopg2.Error as e:
        conn.rollback()
        print(f"❌  Error loading {table_name}: {e}")
    finally:
        cur.close()


def print_row_counts(conn):
    """Print the current row count for every table."""
    tables = ["vendors", "products", "customers", "orders", "payments"]
    cur = conn.cursor()
    print("\n📊  Table Row Counts:")
    print("-" * 40)
    for t in tables:
        cur.execute(f"SELECT COUNT(*) FROM {t}")
        count = cur.fetchone()[0]
        print(f"   {t:<20} : {count:>6,} rows")
    cur.close()
    print("-" * 40)


# =============================================
# Main execution
# =============================================

def main():
    print("=" * 60)
    print("  Multi-Vendor Marketplace — Database Loader")
    print("=" * 60)

    conn = get_connection()

    try:
        # Load order matters because of foreign-key constraints
        load_table(conn, "vendors", "clean_vendors.csv",
                   ["id", "name", "email", "city", "rating", "joined_date"])

        load_table(conn, "products", "clean_products.csv",
                   ["id", "name", "category", "price", "vendor_id", "stock"])

        load_table(conn, "customers", "clean_customers.csv",
                   ["id", "name", "email", "city", "joined_date"])

        load_table(conn, "orders", "clean_orders.csv",
                   ["id", "customer_id", "vendor_id", "order_date",
                    "status", "total_amount", "order_month", "order_year"])

        load_table(conn, "payments", "clean_payments.csv",
                   ["id", "order_id", "method", "status", "amount", "payment_date"])

        print_row_counts(conn)

        print("\n✅  Database loading completed successfully!")
        print("=" * 60)

    except Exception as e:
        print(f"❌  Unexpected error: {e}")
        sys.exit(1)
    finally:
        conn.close()
        print("🔒  Database connection closed.")


if __name__ == "__main__":
    main()
